const API={
    login: '/account/sign-in',
    register: '/account/sign-up',
    forgotpassword: '/account/forgot-password',
    toursOutStanding: 'tour/list',
    // toursComing: 'tour/find',
    // allTours: 'tour/find',
    order: '/order-tours/order',
    tourOrder: '/order-tours/',
    historyOrder: '/order-tours/list',
    updateInfoPersonal: '/customer/update',
    listAddress: '/site/list-address',
    changPassword: '/account/change-password',
    listStatus: '/site/list-status',
    listTour: '/tour/list',
    addTour: '/tour/add',
    listStaff: '/staff/list',
    addStaff: '/staff/add',
    numberTour: '/site/number-tour',
    numberStaff: '/site/number-staff',
    numberOrderOfCustomer: '/order-tours/number-order',
    getInfor: '/site/get-own-infor',
};

export default API;
